name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

     # - name: Set up Xvfb
      #  run: |
       #   sudo apt-get update
        #  sudo apt-get install -y xvfb
         # export DISPLAY=:99
          # Xvfb :99 -screen 0 1024x768x24 &

      - name: Build and test with Maven
        working-directory: ./Arrays
        run: mvn clean install
