name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test with Maven
        working-directory: ./PROG5121_SoftwareDev/ChatMate
        run: mvn clean install

      # - name:  
      #  run: ./gradlew build

      # Optionally, run tests with Maven (if using Maven instead of Gradle)
